### ISSUE TITLE
ngElements including SP-Rest-Proxy

### ISSUE THREAD

**Issue by ARambazamba** [pnp/generator-spfx#108]
#### General Information
* [ ] Usage
* [ ] Development
* [ ] Documentation
* [x ] Feature Request

#### Specific generator
* [ ] Addons
* [ ] HandlebarsJS
ng Elements

Just saw the video about ngElements ... would be great if you also could include Koltyakov's SP-Rest-Proxy or something similar in the Angular Elements Project by default. Would make Angular dev much easier when accessing real SP data :-)

**Comment by phawrylak** [comment]
Hi @ARambazamba, thanks for feedback. This is pretty good idea and I think it's worth implementing. It would allow to use standard `ng serve` and access data in SharePoint. That's pretty nice, because you wouldn't have to use SPFx workbench to develop data access part of your application and could use things like HMR.

**Comment by ARambazamba** [comment]
Hi @phawrylak ... this is exactly what I was thinking of
