### ISSUE TITLE
stylelint addon

### ISSUE THREAD

**Issue by s-KaiNet** [pnp/generator-spfx#125]
#### General Information
* [x] Feature Request

#### Specific generator
* [x] Addons

[stylelint](https://stylelint.io/) is a modern linter for css/sass. OOB SPFx template doesn't have an option to lint styles. I propose to include it via a custom addon.   
Why stylelint? It's a proven and solid way to lint styles. stylelint package has approx 300k downloads per week on npm.   

How I see it:   

If you select a template with .scss files (currently React and Knockout have .scss files), the generator will ask for an additional question - `Additional options` (or something like this, correct wording is debatable) after `Which libraries to include`. There will be a stylelint selection (`Add stylelint (linter for your sass files)`)

**Comment by s-KaiNet** [comment]
Another option (maybe a bit more convenient): 
- Choose your framework [a user selects React or Knockout]

Then: 
  
- ? Additional features
  - ? Which libraries to include:
  - [ ] pnpjs
  - [ ] ....
  - ? Addons
  - [ ] stylelint
  - [ ] other potential addons

As soon as we clarify the format, I will start implementation

**Comment by StfBauer** [comment]
@s-KaiNet great suggestion! Currently working on the upgrade to 1.7 and we should put that on top of that release. This means that you still can implement it because it does not have an impact on the 1.7

Another suggestion I talk to Elio was to add jest testing framework too which implies that we have to think about the selection anyway.

To big problem to join the answer of two questions.

**Comment by StfBauer** [comment]
@s-KaiNet Finally, It is now in thank you very much for the integration in this generator.
