### ISSUE TITLE
Observables in SPFx not working

### ISSUE THREAD

**Issue by ScripTerasu** [pnp/generator-spfx#126]
#### General Information
* [ ] Usage
* [ ] Development
* [x] Bug
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [ ] Addons
* [ ] HandlebarsJS
* [x] Angular Elements

#### What Version you are running?
* NodeJS: v10.13.0
* NPM: 6.4.1
* @pnp/spfx: 1.4.3

#### Observables in SPFx not working

Generate a project to test the functionality of the Observables in Sharepoint but these are not rendered, check network requests and if this is running and getting information but not shown.

[GitHub Project Sample](https://github.com/ScripTerasu/SPFx-Observable-Sample).

**Comment by andrewconnell** [comment]
Rec this issue is closed (re-open if you disagree) this as it's not related to SPFx or the generator at all. It's a known issue with Angular Elements: https://github.com/angular/angular/issues/23841

Fixed by manually forcing change detection. I do this like the following (lots of code omitted for brevity): 

```ts
import { ChangeDetectorRef } from '@angular/core';
//..
export class MissionListComponent implements OnInit {
  constructor(private cdRef: ChangeDetectorRef) { }

  @Output()
  public missionRemoved: EventEmitter<string> = new EventEmitter<string>();

  //..

  public handleRemove(event: IMission) {
    // workaround: force change detection
    this.cdRef.detectChanges();
  }

}
```

**Comment by ScripTerasu** [comment]
It worked correctly
Thank you!
