### ISSUE TITLE
Error while creating SPFx Application Customizer with Angular Element

### ISSUE THREAD

**Issue by gauravgoyal5** [pnp/generator-spfx#134]
I have used following options to create solution :
![image](https://user-images.githubusercontent.com/6926513/49867616-04ab7c00-fe31-11e8-8603-33c7b3cd3bfc.png)

I am getting following error :
![image](https://user-images.githubusercontent.com/6926513/49867813-97e4b180-fe31-11e8-896d-90f491705ec7.png)

I have tried to create project with different name but getting this issue.
Please help me to resolve.

Thanks,
Gaurav Goyal

**Comment by StfBauer** [comment]
Thank you @gauravgoyal5 - I am afraid it is a bug in our generator. Thank you very much for letting us know.

It tries to unlink aka delete a file that does not exist.

This issue is only related to the Application Customizer and this also includes the workaround for now.
You can setup the angular project for now using a web part and add the Application Customizer later.

I currently working on a fix and should be out at least tomorrow

**Comment by StfBauer** [comment]
Should be fixed now.

**Comment by gauravgoyal5** [comment]
Thanks,
When can we get new version with this bug fix?

Thanks,
Gaurav Goyal

**Comment by gauravgoyal5** [comment]
Sorry by mistake I closed it.

**Comment by StfBauer** [comment]
@gauravgoyal5 it is already out. Just make sure you install the latest version of it.

**Comment by gauravgoyal5** [comment]
Thanks. I am upgrading with latest version.
