### ISSUE TITLE
SPFX Angular elements  - How to add second web part in existing solution

### ISSUE THREAD

**Issue by sandippal972258** [pnp/generator-spfx#153]
I have create one spfx project with help of pnp generator using angular elements. it has been successfully created. Now i want to add one another spfx web part in current created solution, so how do i do that with pnp generator.? Is anybody can help me.?

**Comment by gonadn** [comment]
Do not expect that you will get a correct answer here, at least not from any of those ho try to answer here. And you issue will as fast Stefan Bauer can , he will close it with som stupid comment...!! And for you information Angular Elements are buggy project, wont work when you load dynamically data f.ex pnp get data into an array, and try to use *ngFor you will se nothing is rendered. There are bug with Zone rendering....!! even mister Bauer dident no about this issue, he tried to help med with this issue earlier and ended upp that i got feeling of he is just running after closing the issue....!!

My suggestion, do not use or try this bullshitt @pnp/spfx until it is stabil, and bug free...

**Comment by StfBauer** [comment]
To add another web part you can run `yo @pnp/spfx` or `yo @microsoft/SharePoint` from the root folder of your projects or from the project folder named in the format '<your-solutionname>-spfx'.

This will give you the option to add another WebPart or extension:
<img width="956" alt="screenshot 2019-02-11 at 16 42 34" src="https://user-images.githubusercontent.com/5503835/52574209-1b178900-2e1c-11e9-99e3-aa501b742f1a.png">

**Comment by sandippal972258** [comment]
Yes, Its creating SPFX web part in -spfxf folder. but what about angular web part? Do we need to manually create new angular web part for this separate spfx web part? how do we managed multiple web part with multiple angular stuff?

**Comment by gonadn** [comment]
@sandippal972258  this is the most buggy @pnp/spfx generator i ever have been working with, there are alot of issues with zone rendering in angular-elements, and alot of hidden buggs. I have experienced that only project witch posible to create is onwards SPO, ans SP2019. Creating project for 2016 because of this option in generator is buggy. And another thing is that NOTHING is documented when it comes to Angular-Elements. It has experimenting project for a long time know, and all of the mvp's are just making alot of crap/messy code. Witch dosent work properly. They are just there to show how cool developer they are, just to get MVP status.


Forget @pnp/spfx until they have managed to stabil the generator and the creation of projects for on-prem and online enviroments.

Stefan Bauer will close this issue as fast he can by saying that this is a bug or a known issue, and they will fix this in next release....

Do not realy on any thing until it is official announced that it is released and works as asspected....

**Comment by StfBauer** [comment]
@gonadn Can you please submit a PR that fixes the issues concerning Angular Elements. It seems you are way more experienced with Angular Elements than I am.

Thank you for your support.

**Comment by StfBauer** [comment]
@sandippal972258 were you able to create a second web part?

**Comment by StfBauer** [comment]
Closed due to missing feedback.
