### ISSUE TITLE
Installing generator in local folder?

### ISSUE THREAD

**Issue by thomasberman** [pnp/generator-spfx#160]
#### General Information
* [X] Usage
* [ ] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [ ] Addons
* [ ] HandlebarsJS

#### What Version you are running?
* NodeJS: 8.12.0
* NPM: 6.8.0
* @pnp/spfx: 1.6.2

I am only able to install the generator globally - it does not seem to support installing into a local folder like the @microsoft/sharepoint generator. Wondering if this is by design? Typically, I install the @microsoft/sharepoint generator in the project folder I am working on rather than globally.

**Comment by StfBauer** [comment]
Install a generator local is not officially supported and an uncommon scenario for any yeoman generator.
https://yeoman.io/codelab/install-generators.html

There have been made some adjustments to support this scenario specific to the @microsoft/generator-sharepoint but cause troubles in case of the composability model and extensibility model of Yeoman generators.

It is by design of yeoman and this generator to be globally.

**Comment by thomasberman** [comment]
Gotcha, thanks Stefan
