### ISSUE TITLE
Click event isn't fired in IE browser.

### ISSUE THREAD

**Issue by kkurihashi** [pnp/generator-spfx#246]
#### General Information
* [ ] Usage
* [x] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [ ] Addons
* [ ] HandlebarsJS

#### What Version you are running?
* NodeJS: v10.16.0
* NPM: 6.9.0
* @pnp/spfx: 1.12.0

#### Describe your problem
I created 2 components, Angular and Web Part, and added below code in Angular component:
```
<button type="button" (click)="show=!show">{{show ? 'hide' : 'show'}}</button>
<div *ngIf='show'>show</div>
```
Then, I deployed it on SharePoint Workbench, it was perfectly worked in Chrome browser, but not in IE11 browser.
The problem is that button title and div content were not changed after I pushed ‘show’ button.
There are 2 imports in Polyfill.ts in Web Part component on my project.
```
import 'core-js/es6/array';
import 'core-js/es6/reflect';
```
Could you please help me solve this issue?
Thank you.

**Comment by StfBauer** [comment]
Your issue is workbench related and there are multiple issues with IE11. All those issues are out of reach of this generator or project. See [sp-dev-docs](https://github.com/SharePoint/sp-dev-docs/issues?q=is%3Aissue+is%3Aopen+IE11) for IE11 issues.

The better way of testing this is to deploy it to Office 365 and test it there.
